(* ADP (Asterisk Dial Plan) BNF *)

config = (eol|context)*;
  context = "[", ctxname, "]", eol, ctxline*;
    ctxline = [varassign|ext|switch|include|ignorepat], eol;
      varassign = varname, "=", val;
      switch = "switch", ["=>"], val;
      include = "include", ["=>"], ctxname;
      ignorepat = "ignorepat", ["=>"], extname;
      ext = "ext", extname, ("{", applist, "}") | app;
        applist = eol*, app, (eol, [app])*;
        app = [["+"], prio], appname, ("(", appargs, ")") | (",", appargs);
          appargs = val, [("," | "|"), val]*;
        val = (valchars|string|varref)+;
          varref = "${", val, "}";
	  string = '"', '[^"]*', '"'
  eol = [comment], nl;
  comment = ";.*";
  prio = [0-9]+;

ctxname = name;
varname = name;
extname = name;
appname = name;
name = "[-_a-zA-Z0-9]+";
valchars = "[-_a-zA-Z0-9/@:]+";
